export const CALENDAR_DATA = [
  {
    id: "BEFORE_PRESENT",
    name: "Before Present",
    icon: "🦴",
    type: "Computational",
    yearLength: 365.25,
    monthsPerYear: "N/A",
    avgMonthLength: "N/A",
    leapYearFreq: "N/A",
    leapYearPercent: 0,
    color: "bg-stone-500",
    adoptionYear: 1950,
    description: "Years before 1950, used in archaeology and geology",
  },
  {
    id: "COPTIC",
    name: "Coptic",
    icon: "✝️",
    type: "Solar",
    yearLength: 365.25,
    monthsPerYear: 13,
    avgMonthLength: 28.08,
    leapYearFreq: "1 per 4 years",
    leapYearPercent: 25,
    color: "bg-amber-500",
    adoptionYear: 284,
    description: "13 months: 12×30 days + 5-6 day epagomenal period",
  },
  {
    id: "ETHIOPIAN",
    name: "Ethiopian",
    icon: "🇪🇹",
    type: "Solar",
    yearLength: 365.25,
    monthsPerYear: 13,
    avgMonthLength: 28.08,
    leapYearFreq: "1 per 4 years",
    leapYearPercent: 25,
    color: "bg-yellow-500",
    adoptionYear: 1,
    description: "13 months like Coptic, 7-8 year offset from Gregorian",
  },
  {
    id: "FRENCH_REVOLUTIONARY",
    name: "French Revolutionary",
    icon: "🇫🇷",
    type: "Solar",
    yearLength: 365.24225,
    monthsPerYear: 12,
    avgMonthLength: 30,
    leapYearFreq: "Sextile years",
    leapYearPercent: 24.25,
    color: "bg-indigo-500",
    adoptionYear: 1792,
    description: "Decimal calendar from French Revolution, 12×30 days + 5-6",
  },
  {
    id: "GREGORIAN",
    name: "Gregorian",
    icon: "🌍",
    type: "Solar",
    yearLength: 365.2425,
    monthsPerYear: 12,
    avgMonthLength: 30.44,
    leapYearFreq: "97 per 400 years",
    leapYearPercent: 24.25,
    color: "bg-blue-500",
    adoptionYear: 1582,
    description: "Most accurate solar calendar, 400-year leap cycle",
  },
  {
    id: "HEBREW",
    name: "Hebrew",
    icon: "✡️",
    type: "Lunisolar",
    yearLength: 365.25,
    monthsPerYear: "12-13",
    avgMonthLength: 29.53,
    leapYearFreq: "7 per 19 years",
    leapYearPercent: 36.84,
    color: "bg-cyan-500",
    adoptionYear: -3761,
    description: "Lunisolar with leap months to stay aligned with seasons",
  },
  {
    id: "HOLOCENE",
    name: "Holocene",
    icon: "📅",
    type: "Solar",
    yearLength: 365.2425,
    monthsPerYear: 12,
    avgMonthLength: 30.44,
    leapYearFreq: "97 per 400 years",
    leapYearPercent: 24.25,
    color: "bg-green-500",
    adoptionYear: 1993,
    description: "Gregorian calendar offset by +10,000 years",
  },
  {
    id: "ISLAMIC",
    name: "Islamic Civil",
    icon: "☪️",
    type: "Lunar",
    yearLength: 354.37,
    monthsPerYear: 12,
    avgMonthLength: 29.53,
    leapYearFreq: "11 per 30 years",
    leapYearPercent: 36.67,
    color: "bg-emerald-500",
    adoptionYear: 622,
    description: "Pure lunar calendar, drifts 11 days per solar year",
  },
  {
    id: "JULIAN",
    name: "Julian",
    icon: "🏛️",
    type: "Solar",
    yearLength: 365.25,
    monthsPerYear: 12,
    avgMonthLength: 30.44,
    leapYearFreq: "1 per 4 years",
    leapYearPercent: 25,
    color: "bg-purple-500",
    adoptionYear: -45,
    description: "Simple 4-year leap cycle, drifts 1 day per 128 years",
  },
  {
    id: "MAYAN_LONG_COUNT",
    name: "Mayan Long Count",
    icon: "🗿",
    type: "Computational",
    yearLength: 365.25,
    monthsPerYear: "N/A",
    avgMonthLength: "N/A",
    leapYearFreq: "N/A",
    leapYearPercent: 0,
    color: "bg-orange-500",
    adoptionYear: -3114,
    description: "Mesoamerican calendar counting days since creation",
  },
  {
    id: "PERSIAN",
    name: "Persian",
    icon: "🌸",
    type: "Solar",
    yearLength: 365.2422,
    monthsPerYear: 12,
    avgMonthLength: 30.44,
    leapYearFreq: "8 per 33 years",
    leapYearPercent: 24.24,
    color: "bg-rose-500",
    adoptionYear: 1079,
    description: "Most astronomically accurate solar calendar",
  },
  {
    id: "UNIX",
    name: "Unix",
    icon: "💻",
    type: "Computational",
    yearLength: 365.25,
    monthsPerYear: "N/A",
    avgMonthLength: "N/A",
    leapYearFreq: "N/A",
    leapYearPercent: 0,
    color: "bg-gray-500",
    adoptionYear: 1970,
    description: "Seconds since January 1, 1970 00:00:00 UTC",
  },
] as const;
